[tool.poetry]
name = "qrcoder"
version = "1.4.1"
description = "App for creating and reading QR-codes"
authors = ["WENEMOUS TURNIP <novus.lordo.seclorum@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
qrcode = "^8.2"
Pillow = "^10.0.0"
pyqt6 = "^6.9.1"
pywin32 = "^310"
relatorio = "^0.11.1"
pandas = "^2.3.0"
openpyxl = "^3.1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pyinstaller = ">=6.14.1"
