[tool.poetry]
name = "qrcoder"
version = "0.0.1"
description = "App for creating and reading QR-codes"
authors = ["WENEMOUS TURNIP <novus.lordo.seclorum@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pyqt5 = "5.15.10"
pyqt5-qt5 = "5.15.2"
qrcode = "^7.4.2"
Pillow = "^10.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dev-dependencies]
pyinstaller = "^5.13.0"
